### ISSUE TITLE
maybe we could work togather do you know PHP?

### ISSUE THREAD

**Issue by ghost** [YoSmudge/Squeezeit#2]
I am working on a very cool proxy script that uses PHP + CURL, MySQL (for user database if more one user) you are working on a very good project maybe could you help make my project and intergrate your project with mine togather we can be great and your product could become huge

**Comment by YoSmudge** [comment]
I have no idea what you want, PHP is for web-servers not command line. I have no desire to convert this to PHP since it works in it's current form, feel free to do it yourself.
