### ISSUE TITLE
Should preserve IE conditional compilation comments in the minified versions

### ISSUE THREAD

**Issue by ghost** [YoSmudge/Squeezeit#3]
Current implementation of minifying removes all comments. However comments like /_@cc_on @_/,/_@if ... @_/ should be preserved so conditional compilation functionality in IE is preserved.

**Comment by YoSmudge** [comment]
Squeezeit uses [slimmer.py](http://pypi.python.org/pypi/slimmer/) for CSS complication, this is a known issue with slimmer.py. I may move to a different CSS minification method but for now I'm happy with slimmer.py
